<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2023-01-07 14:29:17 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): No connection could be made because the target machine actively refused it.
 D:\xampp\htdocs\logly-api\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2023-01-07 14:29:21 --> Unable to connect to the database
ERROR - 2023-01-07 14:32:40 --> Severity: Warning --> mysqli::real_connect(): MySQL server has gone away D:\xampp\htdocs\logly-api\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2023-01-07 14:32:41 --> Severity: Warning --> mysqli::real_connect(): MySQL server has gone away D:\xampp\htdocs\logly-api\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2023-01-07 14:32:41 --> Severity: Warning --> mysqli::real_connect(): Error while reading greeting packet. PID=22028 D:\xampp\htdocs\logly-api\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2023-01-07 14:32:41 --> Severity: Warning --> mysqli::real_connect(): Error while reading greeting packet. PID=22028 D:\xampp\htdocs\logly-api\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2023-01-07 14:32:41 --> Severity: Warning --> mysqli::real_connect(): (HY000/2006): MySQL server has gone away D:\xampp\htdocs\logly-api\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2023-01-07 14:32:41 --> Severity: Warning --> mysqli::real_connect(): (HY000/2006): MySQL server has gone away D:\xampp\htdocs\logly-api\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2023-01-07 14:32:41 --> Unable to connect to the database
ERROR - 2023-01-07 14:32:41 --> Unable to connect to the database
ERROR - 2023-01-07 14:32:52 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): No connection could be made because the target machine actively refused it.
 D:\xampp\htdocs\logly-api\system\database\drivers\mysqli\mysqli_driver.php 201
ERROR - 2023-01-07 14:32:52 --> Unable to connect to the database
ERROR - 2023-01-07 14:33:54 --> Some variable did not contain a value
ERROR - 2023-01-07 14:33:54 --> Calender Data
ERROR - 2023-01-07 14:33:54 --> Query error: Unknown column 'apple_health' in 'field list' - Invalid query: INSERT INTO `user_activities` (`user_id`, `activity_name`, `activity_id`, `user_activity_profile_id`, `category_id`, `calories`, `measurement_id`, `distance`, `duration`, `streak`, `start_date`, `end_date`, `created_at`, `updated_at`, `apple_health`, `distanceUnit`) VALUES ('657', 'walking', '465', '24', '13', '10', '1', 20.004288377874, 86400, 'true', '2022-12-30', '2022-12-30', '2023-01-07', '2023-01-07 02:33:54', '1', 'km')
